#!/bin/bash

# number 2 and 7 have the best potential

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=14000 --level0_stop_writes_trigger=18000 --compaction_style=0 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=14000 --level0_stop_writes_trigger=18000 --compaction_style=1 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport.csv" > analysis/dbbenchResults/long/WriteHeavyTiered.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=8 --max_background_flushes=10 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=14 --level0_stop_writes_trigger=18 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport1.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled1.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=8 --max_background_flushes=10 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=14 --level0_stop_writes_trigger=18 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport1.csv" > analysis/dbbenchResults/long/WriteHeavyTiered1.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport2.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled2.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport2.csv" > analysis/dbbenchResults/long/WriteHeavyTiered2.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=20 --max_background_flushes=40 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=12 --level0_stop_writes_trigger=15 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport3.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled3.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=20 --max_background_flushes=40 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=12 --level0_stop_writes_trigger=15 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport3.csv" > analysis/dbbenchResults/long/WriteHeavyTiered3.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=5 --max_background_flushes=5 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=10 --level0_stop_writes_trigger=12 --compaction_style=0 --max_background_compactions=5 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport4.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled4.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=5 --max_background_flushes=5 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=10 --level0_stop_writes_trigger=12 --compaction_style=1 --max_background_compactions=5 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport4.csv" > analysis/dbbenchResults/long/WriteHeavyTiered4.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=1342170 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport5.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled5.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=1342170 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport5.csv" > analysis/dbbenchResults/long/WriteHeavyTiered5.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=40 --max_background_flushes=40 --level0_file_num_compaction_trigger=2 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=0 --max_background_compactions=20 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport6.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled6.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=40 --max_background_flushes=40 --level0_file_num_compaction_trigger=2 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=1 --max_background_compactions=20 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport6.csv" > analysis/dbbenchResults/long/WriteHeavyTiered6.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=40 --max_background_flushes=60 --level0_file_num_compaction_trigger=10 --level0_slowdown_writes_trigger=100 --level0_stop_writes_trigger=120 --compaction_style=0 --max_background_compactions=100 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport.csv7" > analysis/dbbenchResults/long/WriteHeavyLeveled7.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=40 --max_background_flushes=60 --level0_file_num_compaction_trigger=10 --level0_slowdown_writes_trigger=100 --level0_stop_writes_trigger=120 --compaction_style=1 --max_background_compactions=100 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport.csv7" > analysis/dbbenchResults/long/WriteHeavyTiered7.txt
#./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=2 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=0 --readwritepercent=95 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/ReadHeavyLeveledReport.csv" > analysis/dbbenchResults/long/ReadHeavyLeveled.txt
#./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db=/"mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=13421700 --max_write_buffer_number=2 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=1 --readwritepercent=95 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/ReadHeavyTieredReport.csv" > analysis/dbbenchResults/long/ReadHeavyTiered.txt

#python3 analysis/src/interval.py