#!/bin/bash
# main run used in the final report with 100,000 keys and 1h long

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=0 --readwritepercent=50 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --report_file="analysis/dbbenchResults/final/WriteHeavyLeveledReport.csv" 1> analysis/dbbenchResults/final/WriteHeavyLeveled.txt 2> analysis/dbbenchResults/final/IntervalWriteHeavyLeveled.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=1 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=0 --readwritepercent=50 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --zipfian=1 --report_file="analysis/dbbenchResults/final/ZipfianWriteHeavyLeveledReport.csv" 1> analysis/dbbenchResults/final/ZipfianWriteHeavyLeveled.txt 2> analysis/dbbenchResults/final/IntervalZipfianWriteHeavyLeveled.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=1 --readwritepercent=50 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --report_file="analysis/dbbenchResults/final/WriteHeavyTieredReport.csv" 1> analysis/dbbenchResults/final/WriteHeavyTiered.txt 2> analysis/dbbenchResults/final/IntervalWriteHeavyTiered.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=1 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=1 --readwritepercent=50 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --zipfian=1 --report_file="analysis/dbbenchResults/final/ZipfianWriteHeavyTieredReport.csv" 1> analysis/dbbenchResults/final/ZipfianWriteHeavyTiered.txt 2> analysis/dbbenchResults/final/IntervalZipfianWriteHeavyTiered.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=0 --readwritepercent=95 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --report_file="analysis/dbbenchResults/final/ReadHeavyLeveledReport.csv" 1> analysis/dbbenchResults/final/ReadHeavyLeveled.txt 2> analysis/dbbenchResults/final/IntervalReadHeavyLeveled.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=1 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=0 --readwritepercent=50 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --zipfian=1 --report_file="analysis/dbbenchResults/final/ZipfianReadHeavyLeveledReport.csv" 1> analysis/dbbenchResults/final/ZipfianReadHeavyLeveled.txt 2> analysis/dbbenchResults/final/IntervalZipfianReadHeavyLeveled.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=1 --readwritepercent=95 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --report_file="analysis/dbbenchResults/final/ReadHeavyTieredReport.csv" 1> analysis/dbbenchResults/final/ReadHeavyTiered.txt 2> analysis/dbbenchResults/final/IntervalReadHeavyTiered.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=1 --duration=3600 --num=100000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=20 --max_background_compactions=4 --compaction_style=1 --readwritepercent=50 --max_background_compactions=4 --report_interval_seconds=1 --stats_interval_seconds=1 --zipfian=1 --report_file="analysis/dbbenchResults/final/ZipfianReadHeavyTieredReport.csv" 1> analysis/dbbenchResults/final/ZipfianReadHeavyTiered.txt 2> analysis/dbbenchResults/final/IntervalZipfianReadHeavyTiered.txt

python3 analysis/src/interval.py