#!/bin/bash

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=50 --level0_stop_writes_trigger=60 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport8.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled8.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=50 --level0_stop_writes_trigger=60 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport8.csv" > analysis/dbbenchResults/long/WriteHeavyTiered8.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=10 --level0_slowdown_writes_trigger=50 --level0_stop_writes_trigger=60 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport9.csv" > analysis/dbbenchResults/long/WriteHeavyLeveledReport9.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=10 --level0_slowdown_writes_trigger=50 --level0_stop_writes_trigger=60 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport9.csv" > analysis/dbbenchResults/long/WriteHeavyTiered9.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=1342170000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=0 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport10.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled10.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=1342170000 --max_write_buffer_number=10 --max_background_flushes=20 --level0_file_num_compaction_trigger=5 --level0_slowdown_writes_trigger=8 --level0_stop_writes_trigger=10 --compaction_style=1 --max_background_compactions=10 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport10.csv" > analysis/dbbenchResults/long/WriteHeavyTiered10.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=1342170000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=18 --level0_stop_writes_trigger=20 --compaction_style=0 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport11.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled11.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=1342170000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=18 --level0_stop_writes_trigger=20 --compaction_style=1 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport11.csv" > analysis/dbbenchResults/long/WriteHeavyTiered11.txt

./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=18 --level0_stop_writes_trigger=20 --compaction_style=0 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyLeveledReport12.csv" > analysis/dbbenchResults/long/WriteHeavyLeveled12.txt
./rocksdb/db_bench --benchmarks="readrandomwriterandom,stats" --db="/mnt/c/temp/rocksdbtest-1000/dbbench" --mmap_read=0 --statistics=1 --histogram=1 --threads=2 --key_size=8 --value_size=1024 --compression_type=none --stats_interval=1000 --use_existing_db=0 --duration=600 --num=1000000000 --write_buffer_size=134217000 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=18 --level0_stop_writes_trigger=20 --compaction_style=1 --readwritepercent=50 --report_interval_seconds=1 --report_file="analysis/dbbenchResults/long/WriteHeavyTieredReport12.csv" > analysis/dbbenchResults/long/WriteHeavyTiered12.txt